language: java
jdk:
- oraclejdk8
env:
  global:
    secure: JV5QZAvqqPcvS9r9ZToCMv51F6VIi9iVSfOmzFVOkmxKiLpo4paqzO3WLpWSunRaUL27/maiS0fj2Ai2ryGFg9IgNtVjaVYT/X561szCd1GWrBfTsHNE/920yuLBkHUe0Te/+rqrwQDIvB2d3E7RLD5Z79wmDgQqnWq5jHzXOttY39ybvLKnPAXLZt+9bRss+UuqknK8HpmeS+2L4sfUxWS8XEK0xqwYhBFNDt764oxfu8d6OtmfBoqTCS5TixcRgYeC6bEBGTpd6BuyIKBiSj588mSftcLJVH7/reN4ULkk8FirpiQCpaoaM58BiPlXWHbjoBHdYDgDigp51JLkk23D7iLPl4mR2QjNngpoyi10VsSrx79zFM8jI4xOY0BpheiRsB3UBAcmL93OnOnJKqKUZCLJfZXalN120WdQGZv4wqGdfKzxR170uUMW+2IwCReGcfmHoMzrtCxIL4E0EL1Imfw5APt9R9ps9iXsYrhlY6oJG3uOPgLphiafNYV+wnPkgiFW3crP0Ep+WhCOUgmHnRN5D0dJkvEcTXB2nBZLiFoNRa+ET4KCUwTds/2K7Usjn1cqp0V3L+p4ZIJ98O7HUJS8MDOeUtINDdR/zqlfH7H72q76wZKQzO8aqPp97hA6CIyRn3E8UBVIxnzrWMQB03HyfTxG8yN4hQO+aak=
